# Generated by Django 4.1 on 2022-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regionmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=15)),
                ('region_name', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('Unknown', 'Unknown'), ('India', 'India'), ('USA', 'USA'), ('Japan', 'Japan'), ('China', 'China'), ('Cambodia', 'Cambodia'), ('Rwanda', 'Rwanda'), ('Thailand', 'Thailand')], default='Unknown', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='region_image')),
            ],
        ),
    ]
