# Generated by Django 4.1 on 2022-08-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_regionmodel_region_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmodel',
            old_name='region_code',
            new_name='code',
        ),
    ]
