# Generated by Django 4.1 on 2022-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_regionmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='image',
            field=models.ImageField(upload_to='region_image'),
        ),
    ]
