# Generated by Django 4.1 on 2022-08-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_regionmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='country',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'India'), ('2', 'USA'), ('3', 'Japan'), ('4', 'China'), ('5', 'Cambodia'), ('Rwanda', '6'), ('7', 'Thailand')], max_length=30),
        ),
    ]
